FROM apache/airflow:latest

USER root
RUN apt-get update && \
    apt-get -y install git && \
    apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev gcc g++ && \
    apt-get clean 
CMD 
USER airflow

COPY requirements.txt /tmp/requirements.txt 
RUN pip install -r /tmp/requirements.txt
